import streamlit as st

# Define all challenges and their respective guides
challenges = {
    "Bandit": [
        ("Hold up 5 townsfolk", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
        ("Rob 2 coaches or return 2 stolen coaches to a Fence", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
        ("Rob the cash register in any 4 shops in 1 day", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
        ("Rob 3 coaches or return 3 stolen coaches to a Fence in 1 day", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
        ("Amass a $250 bounty in one state", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
        ("Steal 5 horses and sell them to the Horse Fence at Clemens Cove", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
        ("Rob $50 worth of cash and valuables from townsfolk and travellers", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
        ("Steal 7 wagons and sell them to the Fence at Emerald Ranch", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
        ("Hogtie someone and leave them on the railroad 3 times", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
        ("Complete 5 train robberies without dying or being caught", "https://www.rdr2.org/guides/bandit-challenges-guide/"),
    ],
    "Explorer": [
        ("Find a treasure from a treasure map", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
        ("Find 5 treasures from treasure maps", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
        ("Complete all treasure hunts", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
        ("Find a total of 10 treasures", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
        ("Collect all cigarette cards", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
        ("Complete the Poisonous Trail treasure hunt", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
        ("Complete the Jack Hall Gang treasure hunt", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
        ("Complete the High Stakes treasure hunt", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
        ("Find the Legendary Panther", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
        ("Complete the Legendary Fish challenge", "https://www.rdr2.org/guides/explorer-challenges-guide/"),
    ],
    "Gambler": [
        ("Win 5 hands of Poker", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
        ("Double down and win 5 times in Blackjack", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
        ("Win 3 games of Five Finger Fillet", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
        ("Bust out each Poker location", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
        ("Win 3 rounds of Dominoes without drawing any tiles", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
        ("Beat the Blackjack dealer in two locations", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
        ("Beat the Five Finger Fillet player in every location", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
        ("Win 3 hands of Blackjack with three hits or more", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
        ("Win 3 consecutive games of Dominoes", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
        ("Win three hands of Poker in a row", "https://www.rdr2.org/guides/gambler-challenge-guide/"),
    ],
    "Herbalist": [
        ("Pick 6 Yarrow", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
        ("Pick and eat 4 species of berry", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
        ("Craft 7 items using Sage as an ingredient", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
        ("Pick 5 mushrooms and feed them to your horse", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
        ("Craft 9 items using Indian Tobacco as an ingredient", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
        ("Pick 15 different species of herb", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
        ("Craft and use 5 special miracle tonics", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
        ("Use Oleander to craft 6 poison weapons", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
        ("Pick one of each species of herb", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
        ("Season and cook all 11 types of meat", "https://www.rdr2.org/guides/herbalist-challenge-guide/"),
    ],
    "Horseman": [
        ("Kill 5 rabbits from horseback", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
        ("Jump over 3 obstacles in 15 seconds", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
        ("Ride from Valentine to Rhodes in less than 5 minutes", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
        ("Drag a victim 3300 feet with your lasso while mounted", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
        ("Trample 5 animals while on horseback", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
        ("Ride from Strawberry to Saint Denis in less than 9 minutes without touching any water", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
        ("Kill 7 enemies from horseback without dismounting", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
        ("Kill 9 predators from horseback", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
        ("Ride from Van Horn to Blackwater in less than 17 minutes without touching any water", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
        ("Break every wild horse breed", "https://www.rdr2.org/guides/horseman-challenges-guide/"),
    ],
    "Master Hunter": [
        ("Skin 3 deer", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
        ("Collect 3 perfect quality rabbit pelts", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
        ("Track 10 different animal species using your binoculars", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
        ("Call an animal and get a clean kill 5 times", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
        ("Skin 3 black or grizzly bears", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
        ("Kill 5 cougars with your bow", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
        ("Use bait to lure and kill both a predator and a herbivore", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
        ("Catch 3 fish with no bait", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
        ("Hunt and kill the Legendary Buck", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
        ("Kill 10 Legendary Animals", "https://www.rdr2.org/guides/master-hunter-challenges-guide/"),
    ],
    "Sharpshooter": [
        ("Kill 3 flying birds", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
        ("Kill 2 different species of animal in 1 Dead Eye use", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
        ("Kill 5 flying birds while on a moving train", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
        ("Kill someone at 80 feet away with a tomahawk", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
        ("Kill 6 animals without switching or reloading your weapon", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
        ("Kill someone at least 660 feet away with a long scoped rifle", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
        ("Get 7 headshots in a row", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
        ("Disarm 3 enemies without reloading or switching your weapon", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
        ("Shoot 3 people’s hats off in the same Dead Eye use", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
        ("Kill 3 flying birds with 3 consecutive long scoped rifle shots", "https://www.rdr2.org/guides/sharpshooter-challenges-guide/"),
    ],
    "Survivalist": [
        ("Catch 3 Bluegill fish", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
        ("Hand 5 animals into camp or trapper", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
        ("Kill 5 animals with a varmint rifle", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
        ("Craft a dynamite, fire, improved, poison, and small game arrow", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
        ("Catch a fish in the Bayou from a riverboat and while standing on train tracks", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
        ("Kill a scavenging animal while it is feeding a corpse 5 times", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
        ("Kill 8 small game animals with consecutive shots, using small game arrows", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
        ("Craft a homing tomahawk, improved tomahawk, volatile dynamite, and volatile fire bottle", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
        ("Catch a fish that weighs at least 19lb", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
        ("Catch one of each type of fish throughout the world", "https://www.rdr2.org/guides/survivalist-challenges-guide/"),
    ],
    "Weapons Expert": [
        ("Kill 3 enemies with a knife", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
        ("Kill 3 enemies in 10 seconds using only throwing knives", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
        ("Kill 3 birds of prey using only a tomahawk", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
        ("Kill 10 enemies with a shotgun using crafted ammo", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
        ("Kill 5 mounted enemies, using 1 throwing knife per kill", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
        ("Kill 4 enemies at the same time with a single stick of dynamite", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
        ("Kill 4 consecutive enemies by throwing and retrieving the same tomahawk", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
        ("Kill 15 enemies using a long-barrelled shotgun", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
        ("Kill 9 unaware enemies from behind, using the bow", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
        ("Kill a grizzly bear without taking damage, using only throwing knives", "https://www.rdr2.org/guides/weapons-expert-challenges-guide/"),
    ],
}

# Create selection boxes
category = st.selectbox("Select Challenge Category", list(challenges.keys()))
number = st.selectbox("Select Challenge Number", list(range(1, 11)))

# Display the selected challenge details
challenge, guide_link = challenges[category][number - 1]
st.write(f"Challenge {number}: {challenge}")
st.write(f"[Guide Link]({guide_link})")
